---
- hosts: all
  become: yes
  gather_facts: false
  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes
    
    - name: Install packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-tk
          - apache2
          - libapache2-mod-php
          - php
          - php-mysql
        state: present
    
    - name: Add project repository
      git:
        repo: https://github.com/HimeYN/WarwaitCap.git
        dest: /home/ubuntu/WarwaitCap

    - name: Enable php module 
      command: a2enmod php8.1
      
    - name: Install requirements
      command: pip install -r WarwaitCap/Projet/requirements.txt

    - name: Run Python App
      command: python3 Setupwith.py
    
