---
- hosts: all
  become: yes
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
    
    - name: Install packages
      apt:
        name:
          - git
          - mysql-server
          - python3
          - python3-pip
          - apache2
          - libapache2-mod-php
          - php
          - php-mysql
        state: present

    - name: Add project repository
      git:
        repo: https://github.com/HimeYN/WarwaitCap.git
        dest: /home/ubuntu/WarwaitCap/

    - name: Copy Matrice des competences
      copy:
        src: /home/ubuntu/Matrice_des_competences.xlsx
        dest: /home/ubuntu/WarwaitCap/AppPython

    - name: Copy Wait_Room_2023
      copy:
        src: /home/ubuntu/Wait_Room_2023.xlsx
        dest: /home/ubuntu/WarwaitCap/AppPython

  
    - name: Set the requirements
      command: pip install -r WarwaitCap/Projet/requirements.txt

    - name: Create MySQL Databases
      mysql_db:
        name: "{{ item }}"
        state: present
      loop: "{{ databases }}"

    - name: Create MySQL User and Grant all priviledges
      mysql_user:
        name: "{{ mysql_user_name }}"
        password: "{{ mysql_user_password }}"
        priv: "*.*:ALL,GRANT"
        state: present

    - name: Initialiaze BDDs
      command: bash Warwait/configure.sh

    - name: Restart Apache Server
      service:
        name: apache2
        state: restarted
