---
- hosts: all
  become: yes
  gather_facts: false
  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes
    
    - name: Install packages
      apt:
        name:
          - git
          - mysql-server
          - python3
          - python3-pip
          - apache2
          - libapache2-mod-php
          - php
          - php-mysql
        state: present
    
    - name: Add project repository
      git:
        repo: https://github.com/HimeYN/WarwaitCap.git
        dest: /home/ubuntu/WarwaitCap
  
    - name: Run Python script
      command: pip install -r WarwaitCap/Projet/requirements.txt
    
    - name: Copy file
      copy:
        src: /home/ubuntu
        dest: /home/ubuntu/WarwaitCap/AppPython
